#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-rack-protection
Version  : 1.5.3
Release  : 2
URL      : https://rubygems.org/downloads/rack-protection-1.5.3.gem
Source0  : https://rubygems.org/downloads/rack-protection-1.5.3.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-rack
BuildRequires : rubygem-rack-test
BuildRequires : rubygem-rdoc

%description
You should use protection!
This gem protects against typical web attacks.
Should work for all Rack apps, including Rails.

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n rack-protection-1.5.3
gem spec %{SOURCE0} -l --ruby > rubygem-rack-protection.gemspec

%build
gem build rubygem-rack-protection.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
rack-protection-1.5.3.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.2.0/cache/rack-protection-1.5.3.gem
/usr/lib64/ruby/gems/2.2.0/doc/rack-protection-1.5.3/ri/Rack/Protection/AuthenticityToken/accepts%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rack-protection-1.5.3/ri/Rack/Protection/AuthenticityToken/cdesc-AuthenticityToken.ri
/usr/lib64/ruby/gems/2.2.0/doc/rack-protection-1.5.3/ri/Rack/Protection/Base/accepts%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rack-protection-1.5.3/ri/Rack/Protection/Base/app-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rack-protection-1.5.3/ri/Rack/Protection/Base/call-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rack-protection-1.5.3/ri/Rack/Protection/Base/cdesc-Base.ri
/usr/lib64/ruby/gems/2.2.0/doc/rack-protection-1.5.3/ri/Rack/Protection/Base/default_options-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rack-protection-1.5.3/ri/Rack/Protection/Base/default_options-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rack-protection-1.5.3/ri/Rack/Protection/Base/default_reaction-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rack-protection-1.5.3/ri/Rack/Protection/Base/default_reaction-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rack-protection-1.5.3/ri/Rack/Protection/Base/deny-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rack-protection-1.5.3/ri/Rack/Protection/Base/drop_session-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rack-protection-1.5.3/ri/Rack/Protection/Base/encrypt-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rack-protection-1.5.3/ri/Rack/Protection/Base/html%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rack-protection-1.5.3/ri/Rack/Protection/Base/instrument-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rack-protection-1.5.3/ri/Rack/Protection/Base/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rack-protection-1.5.3/ri/Rack/Protection/Base/options-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rack-protection-1.5.3/ri/Rack/Protection/Base/origin-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rack-protection-1.5.3/ri/Rack/Protection/Base/random_string-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rack-protection-1.5.3/ri/Rack/Protection/Base/react-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rack-protection-1.5.3/ri/Rack/Protection/Base/referrer-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rack-protection-1.5.3/ri/Rack/Protection/Base/report-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rack-protection-1.5.3/ri/Rack/Protection/Base/safe%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rack-protection-1.5.3/ri/Rack/Protection/Base/session%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rack-protection-1.5.3/ri/Rack/Protection/Base/session-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rack-protection-1.5.3/ri/Rack/Protection/Base/warn-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rack-protection-1.5.3/ri/Rack/Protection/EscapedParams/call-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rack-protection-1.5.3/ri/Rack/Protection/EscapedParams/cdesc-EscapedParams.ri
/usr/lib64/ruby/gems/2.2.0/doc/rack-protection-1.5.3/ri/Rack/Protection/EscapedParams/escape-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rack-protection-1.5.3/ri/Rack/Protection/EscapedParams/escape_hash-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rack-protection-1.5.3/ri/Rack/Protection/EscapedParams/escape_string-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rack-protection-1.5.3/ri/Rack/Protection/EscapedParams/handle-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rack-protection-1.5.3/ri/Rack/Protection/EscapedParams/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rack-protection-1.5.3/ri/Rack/Protection/FormToken/accepts%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rack-protection-1.5.3/ri/Rack/Protection/FormToken/cdesc-FormToken.ri
/usr/lib64/ruby/gems/2.2.0/doc/rack-protection-1.5.3/ri/Rack/Protection/FrameOptions/call-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rack-protection-1.5.3/ri/Rack/Protection/FrameOptions/cdesc-FrameOptions.ri
/usr/lib64/ruby/gems/2.2.0/doc/rack-protection-1.5.3/ri/Rack/Protection/FrameOptions/frame_options-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rack-protection-1.5.3/ri/Rack/Protection/HttpOrigin/accepts%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rack-protection-1.5.3/ri/Rack/Protection/HttpOrigin/base_url-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rack-protection-1.5.3/ri/Rack/Protection/HttpOrigin/cdesc-HttpOrigin.ri
/usr/lib64/ruby/gems/2.2.0/doc/rack-protection-1.5.3/ri/Rack/Protection/IPSpoofing/accepts%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rack-protection-1.5.3/ri/Rack/Protection/IPSpoofing/cdesc-IPSpoofing.ri
/usr/lib64/ruby/gems/2.2.0/doc/rack-protection-1.5.3/ri/Rack/Protection/JsonCsrf/call-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rack-protection-1.5.3/ri/Rack/Protection/JsonCsrf/cdesc-JsonCsrf.ri
/usr/lib64/ruby/gems/2.2.0/doc/rack-protection-1.5.3/ri/Rack/Protection/JsonCsrf/has_vector%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rack-protection-1.5.3/ri/Rack/Protection/PathTraversal/call-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rack-protection-1.5.3/ri/Rack/Protection/PathTraversal/cdesc-PathTraversal.ri
/usr/lib64/ruby/gems/2.2.0/doc/rack-protection-1.5.3/ri/Rack/Protection/PathTraversal/cleanup-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rack-protection-1.5.3/ri/Rack/Protection/RemoteReferrer/accepts%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rack-protection-1.5.3/ri/Rack/Protection/RemoteReferrer/cdesc-RemoteReferrer.ri
/usr/lib64/ruby/gems/2.2.0/doc/rack-protection-1.5.3/ri/Rack/Protection/RemoteToken/accepts%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rack-protection-1.5.3/ri/Rack/Protection/RemoteToken/cdesc-RemoteToken.ri
/usr/lib64/ruby/gems/2.2.0/doc/rack-protection-1.5.3/ri/Rack/Protection/SessionHijacking/accepts%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rack-protection-1.5.3/ri/Rack/Protection/SessionHijacking/cdesc-SessionHijacking.ri
/usr/lib64/ruby/gems/2.2.0/doc/rack-protection-1.5.3/ri/Rack/Protection/SessionHijacking/encrypt-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rack-protection-1.5.3/ri/Rack/Protection/XSSHeader/call-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rack-protection-1.5.3/ri/Rack/Protection/XSSHeader/cdesc-XSSHeader.ri
/usr/lib64/ruby/gems/2.2.0/doc/rack-protection-1.5.3/ri/Rack/Protection/cdesc-Protection.ri
/usr/lib64/ruby/gems/2.2.0/doc/rack-protection-1.5.3/ri/Rack/Protection/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rack-protection-1.5.3/ri/Rack/Protection/version-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rack-protection-1.5.3/ri/Rack/cdesc-Rack.ri
/usr/lib64/ruby/gems/2.2.0/doc/rack-protection-1.5.3/ri/cache.ri
/usr/lib64/ruby/gems/2.2.0/gems/rack-protection-1.5.3/License
/usr/lib64/ruby/gems/2.2.0/gems/rack-protection-1.5.3/README.md
/usr/lib64/ruby/gems/2.2.0/gems/rack-protection-1.5.3/Rakefile
/usr/lib64/ruby/gems/2.2.0/gems/rack-protection-1.5.3/lib/rack-protection.rb
/usr/lib64/ruby/gems/2.2.0/gems/rack-protection-1.5.3/lib/rack/protection.rb
/usr/lib64/ruby/gems/2.2.0/gems/rack-protection-1.5.3/lib/rack/protection/authenticity_token.rb
/usr/lib64/ruby/gems/2.2.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb
/usr/lib64/ruby/gems/2.2.0/gems/rack-protection-1.5.3/lib/rack/protection/escaped_params.rb
/usr/lib64/ruby/gems/2.2.0/gems/rack-protection-1.5.3/lib/rack/protection/form_token.rb
/usr/lib64/ruby/gems/2.2.0/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb
/usr/lib64/ruby/gems/2.2.0/gems/rack-protection-1.5.3/lib/rack/protection/http_origin.rb
/usr/lib64/ruby/gems/2.2.0/gems/rack-protection-1.5.3/lib/rack/protection/ip_spoofing.rb
/usr/lib64/ruby/gems/2.2.0/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb
/usr/lib64/ruby/gems/2.2.0/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb
/usr/lib64/ruby/gems/2.2.0/gems/rack-protection-1.5.3/lib/rack/protection/remote_referrer.rb
/usr/lib64/ruby/gems/2.2.0/gems/rack-protection-1.5.3/lib/rack/protection/remote_token.rb
/usr/lib64/ruby/gems/2.2.0/gems/rack-protection-1.5.3/lib/rack/protection/session_hijacking.rb
/usr/lib64/ruby/gems/2.2.0/gems/rack-protection-1.5.3/lib/rack/protection/version.rb
/usr/lib64/ruby/gems/2.2.0/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb
/usr/lib64/ruby/gems/2.2.0/gems/rack-protection-1.5.3/rack-protection.gemspec
/usr/lib64/ruby/gems/2.2.0/gems/rack-protection-1.5.3/spec/authenticity_token_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/rack-protection-1.5.3/spec/base_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/rack-protection-1.5.3/spec/escaped_params_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/rack-protection-1.5.3/spec/form_token_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/rack-protection-1.5.3/spec/frame_options_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/rack-protection-1.5.3/spec/http_origin_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/rack-protection-1.5.3/spec/ip_spoofing_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/rack-protection-1.5.3/spec/json_csrf_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/rack-protection-1.5.3/spec/path_traversal_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/rack-protection-1.5.3/spec/protection_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/rack-protection-1.5.3/spec/remote_referrer_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/rack-protection-1.5.3/spec/remote_token_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/rack-protection-1.5.3/spec/session_hijacking_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/rack-protection-1.5.3/spec/spec_helper.rb
/usr/lib64/ruby/gems/2.2.0/gems/rack-protection-1.5.3/spec/xss_header_spec.rb
/usr/lib64/ruby/gems/2.2.0/specifications/rack-protection-1.5.3.gemspec
